hello:
   vicky: Hello Vicky
my:
   app: Spring Boot Config
   dbvalue: "{url: 'http://localhost:8080/restdb', username:'vicky',pass:'pass'}"
app:
   discription: Welcome to ${my.app}
#This properties can be overide by creting application.properties (same name) and keep with paraller
#to jar
#And we can also provide commad line argumant to overide properties
#java -jar jar_name --hello.vicky: "Hello Vicky"
list.value: one,two,three
#Reading value as key value pair
   

db:
   connection: "{url:'http://localhost:8080/restdb', username:'vicky',pass:'pass'}"
   host: 127.0.0.1
   port: 9999

#this will expose every porperties on this endpoints http://localhost:8080/actuator/configprops
# we can expose selective properties
#spring.application.name=spring-boot-confi is the name of microsercie and create spring-boot-confi.yml on
#spring cloud config server. it will used only for that microservice
management.endpoints.web.exposure.include: "*"
spring:
  profiles:
    active:
    - test
